version: '3.8'

services:
  postgresql:
    image: postgres:15
    container_name: postgresql-spring-sea-salt
    restart: always
    environment:
      POSTGRES_DB: spring-sea-salt
      POSTGRES_USER: sea_salt_user
      POSTGRES_PASSWORD: sea_salt_password
      POSTGRES_ROOT_PASSWORD: root_password
    ports:
      - "7777:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sea_salt_user -d spring-sea-salt"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-spring-sea-salt
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@seasalt.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - postgresql
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgresql_data:
  pgadmin_data: