version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb-srping-sea-salt
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: spring-sea-salt
      MARIADB_USER: sea_salt_user
      MARIADB_PASSWORD: sea_salt_password
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro

volumes:
  mariadb_data: